tasks:
  - init: >
      yarn install &&
      yarn run build
    command: >
      gp sync-done bundlebuild &&
      yarn run start
  - init: >
      cd example &&
      yarn install &&
      yarn run build
    command: >
      gp sync-await bundlebuild &&
      yarn run start
